<?php return array(
    'root' => array(
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => '4db5d13b3ded02323b8e327676f91e5ab18ec0ec',
        'name' => '__root__',
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => '4db5d13b3ded02323b8e327676f91e5ab18ec0ec',
            'dev_requirement' => false,
        ),
        'bcosca/fatfree-core' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../bcosca/fatfree-core',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => 'd03a6f74280532f855a39fd5872d0ef3f9c821d9',
            'dev_requirement' => false,
        ),
        'google/recaptcha' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/recaptcha',
            'aliases' => array(),
            'reference' => 'e7add3be59211482ecdb942288f52da64a35f61a',
            'dev_requirement' => false,
        ),
        'madcoda/php-youtube-api' => array(
            'pretty_version' => 'v1.2.5',
            'version' => '1.2.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../madcoda/php-youtube-api',
            'aliases' => array(),
            'reference' => 'eac4b82e9f6d4377964e0e735aba59c51e42bd5e',
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.5.0',
            'version' => '6.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'reference' => 'a5b5c43e50b7fba655f793ad27303cd74c57363c',
            'dev_requirement' => false,
        ),
        'respect/validation' => array(
            'pretty_version' => '0.9.8',
            'version' => '0.9.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../respect/validation',
            'aliases' => array(),
            'reference' => '7d978d64e33e522b060ef82d1d41c39e60f28959',
            'dev_requirement' => false,
        ),
    ),
);
